### ISSUE TITLE
Список наград

### ISSUE THREAD

**Issue by formatq** [abrikoseg/Axenia#10]
По команде /rewards выводить список наград.
В приватном чате выводить список наград в каждом чате. Лимит 3 чата. Сортировка по убыванию кармы в чате.
В группвом чате выводить награды только этого чата.
Учесть что наград может не быть.

**Comment by formatq** [comment]
@formatq круто

**Comment by abrikoseg** [comment]
@formatq количество чатов, в которых сидит пользователь. Минимум кармы, максимум кармы, среднееарифметическое

**Comment by formatq** [comment]
команда /stats

**Comment by formatq** [comment]
#19
