### ISSUE TITLE
Удаление чата из БД при удалении бота из неё

### ISSUE THREAD

**Issue by abrikoseg** [abrikoseg/Axenia#14]

**Comment by formatq** [comment]
Вместе с кармой пользователей?

**Comment by abrikoseg** [comment]
Не, пусть пользователи с кармой хранятся, вдруг со психу или нечайно удалили

**Comment by abrikoseg** [comment]
Бот не получает обновления, когда его удаляют, может исправят когда-нибудь. Напишу в саппорт.

**Comment by formatq** [comment]
> Напишу в саппорт.
Есть ответ?

**Comment by formatq** [comment]
> Добавить поле в Chats. При удалении бота из чата выставлять флаг что чат не активный. При добавлении флаг менять.
Удаление может привести к нарушению целостности, хотя у нас вроде внешние ключи нигде не настроены. Но помечать как "удаленный", вместо физического удаления - хорошая практика

**Comment by abrikoseg** [comment]
@formatq Неа. Задали уточняющий вопрос и замолчали
