### ISSUE TITLE
Администраторы бота

### ISSUE THREAD

**Issue by formatq** [abrikoseg/Axenia#18]
При добавлении бота в чат добавляющий пользователь назначается администратором.
Если бот уже присутствовал, то не назначается.
Другой администратор может сделать другого пользователя администратором.

Возможно ситуация. 
ю1 добавил бота впервые, стал админом.
ю1 удалился/кикнули/забанили - ю1 перестал быть админом.
Админов нет. Как назначать администратора?

**Comment by abrikoseg** [comment]
@formatq Добавить бота заново
