### ISSUE TITLE
Покупка контента за карму

### ISSUE THREAD

**Issue by abrikoseg** [abrikoseg/Axenia#21]

**Comment by abrikoseg** [comment]
@abrikoseg При нажатии на команду /buy. Появляется сообщение с расценками, и кнопки для покупки. При нажатии на кнопку, у юзера снимается карма, в сообщении появляется контент с надписью "такой то купил".

**Comment by abrikoseg** [comment]
Покупать можно сиськи и жопы (при включеном NSFW), а также котят, гэги, может интересные статьи, коубы, гифки, видосы и т.д.

**Comment by formatq** [comment]
при команде /buy если не включен NSFW, выводить сообщение о том что такое доступно только в NSFW режиме

**Comment by abrikoseg** [comment]
@formatq да просто не выводить отдельные товары кнопки

**Comment by abrikoseg** [comment]
прикрутить голосовалку с привязкой к апи 
vote for boobs: "/boobs/vote/{id=0}/{operation=plus;[plus,minus]}/", example: "/boobs/vote/6202/minus/" - negative vote for boobs with id 6202;
