### ISSUE TITLE
Система траты кармы

### ISSUE THREAD

**Issue by formatq** [abrikoseg/Axenia#7]
Накопленную карму тратить на всяческие плюшки:
1. Прелестное слово от Аксиньи при плюсовании или минусовании 
пример <b>Красавчег</b> abrikos (1067.1) плюсанул в карму formatq (875.1).
2. Доступ к командам, на которые Аксинья будет, например, бубсы или котиков выдавать до определенной даты или определенное количесво раз. Анегдоты травить, башорг кидать по фразе какой-нить.

При этом награды должны оставаться. Один раз получил и навсегда.

**Comment by formatq** [comment]
3. Самому назначать сколько начислить кармы ( + 4, - 5)
4. Поделиться кармой - отдать част своей кармы - пожертвовать

**Comment by abrikoseg** [comment]
Cyril Fomenko 🍊‮, [26.04.16 20:00]
боты же ща умеют редактировать сообщения и создавать кнопки под сообщением

Cyril Fomenko 🍊‮, [26.04.16 20:01]
можно это использовать в качестве диалога подтверждения траты кармы
