### ISSUE TITLE
Локализация бота

### ISSUE THREAD

**Issue by formatq** [abrikoseg/Axenia#8]
Нужно прикрутить локализацию.

**Comment by abrikoseg** [comment]
Добавить поля lang в таблицы Groups и Users. Первоначально они пустые. При получении команды /start пользователю приходит выбор языка. Когда тот делает выбор - поле lang заполняется. Когда пользователь добавляет бота в группу, поле lang группы заполняется значением поля lang пользователя, который пригласил пользователя.

**Comment by formatq** [comment]
@abrikoseg давай сразу default сделаем EN

**Comment by abrikoseg** [comment]
@formatq по умолчанию у юзера пустота в таблице

**Comment by formatq** [comment]
Сделано
